### ISSUE TITLE
Uninstallation

### ISSUE THREAD

**Issue by Cronanius** [manns/pyspread#117]
For the install from source tarball, there is no way of figuring out how to uninstall pyspread. Would it be possible to perhaps generate an "uninstall" script? Or at least an explanation of how/where it has been installed so that it could be manually uninstalled (likely not fun). Thanks!

**Comment by manns** [comment]
I assume that you are using the tarball.
Have you tried installing pyspread via pip?
pip has an uninstall option.

**Comment by Cronanius** [comment]
I have never even heard of pip. I'll have a look!
