### ISSUE TITLE
Add XDG desktop file

### ISSUE THREAD

**Issue by dumblob** [manns/pyspread#118]
Please add [XDG desktop](http://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html) file to make pyspread appear in menus, lists, etc. and test it with Gnome/KDE.

**Comment by manns** [comment]
An XDG desktop file is already present in the git repository. You can find it at:
https://github.com/manns/pyspread/blob/master/pyspread/pyspread.desktop

It has been used by several distributions e.g. by Debian and seems to work so far.

**Comment by dumblob** [comment]
Right. Could you please then add to `setup.py` another command target `
cmdclass={'install': lcrs_install}` (the method `lcrs_install.run()` should contain something like `os.system('xdg-desktop-menu install data/lcrs-master.desktop')`) as shown e.g. in https://github.com/benjaoming/lcrs/blob/master/setup.py ?

**Comment by manns** [comment]
I have doubts that your solution for lcrs may one day cause cross platform issues because command line syntax or path assumptions might differ for other operating systems.

If you need xdg support and if you write the new target class "xdg" using pyxdg as an optional dependency then I would integrate it into pyspread.

**Comment by dumblob** [comment]
It's a minor issue and I think it's not necessary to add another dependency. Maybe just detect if it's a unix-like system or not and if it is, then just grab the first path in the environment variable `$XDG_DATA_DIRS` which contains the subdirectory `applications/` (according to the [XDG Base Directory Specification](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html), `/usr/local/share/:/usr/share/` should be used as fallback and the `applications/` subdirectory created inside) and put the `*.desktop` file there. Of course, care must be taken with installation prefix.

But right now it's not a priority -> closing.
