### ISSUE TITLE
moving the mouse over a button is enough to execute the code inside the cell (pyspread 1.0.3)

### ISSUE THREAD

**Issue by fayce66** [manns/pyspread#133]
Sometimes moving the mouse over a cell button is just enough to execute the code inside the cell, which is probably not what it's supposed to do. I tried to lock/unlock the cell button but it does not change the behavior.

Also, I also notice that sometimes clicking the first time in a cell button does not execute the code inside the cell, so it's a little bit confusing. I need to click at least 2 times to execute the code. I don't know if both problems are related.

I am using the following wxWidgets version:
**python-wxgtk3.0  3.0.2.0+dfsg-1build1 amd64 Python interface to the wxWidgets Cross-platform C++ GUI toolkit**

**System:  Host: xxx Kernel: 4.4.0-22-generic x86_64 (64 bit gcc: 5.3.1) Desktop: Xfce 4.12.3 (Gtk 2.24.28)
 Distro: Ubuntu 16.04 xenial**

**Comment by manns** [comment]
I have not been able to reproduce the exact behavior on Debian Linux (unstable) using pyspread 1.0.3 with wx version 3.0.2.0 gtk2 (classic) with the attached zipped test file [buttontest.zip](https://github.com/manns/pyspread/files/312931/buttontest.zip).

I found the following glitches though:
 + When the mouse stops over the button before first execution then a tooltip is generated that shows the cell result. This tooltip causes the button cell to be executed. I have disabled tooltips for button cells and frozen cells in the 1.1 branch.
 + The former behavior should also occur if the cell cache is exceeded, i.e. if many thousand cells are filled in the spreadsheet. Then the tooltip may again execute the button cell code.
 + Double clicks are interpreted as single clicks by the button cell. I doubt that this is a practical issue.

**Comment by fayce66** [comment]
Hi Martin,

I tried your buttontest file with version 1.1 and I have the following
issues:
- when the tooltip appears, and I click in another cell, the button code
get executed and the result cell is updated.
- sometimes when I click just once in the button (coming from another
cell), nothing happens (i.e the result cell is not executed), but it seems
that sometimes clicking away triggers the button macro and the result cell
is updated. It's not systematic, maybe clicking once trigger the tooltip
but it's not displayed on the screen)
- I renamed your button [test++] and I added a button [test--] with
"i=i-1". Now this is interesting:
    a/ the first time I restarted the spreadsheet, the result cell i=0.
When I clicked in a random cell (not the buttons), the [test--] button was
triggered and the result cell i displayed -1. After that, restarting the
spreadsheet did not trigger any action and the result cell was still 0.
    b/ without EVER clicking in any of the buttons, I just put my mouse
over [test++], see the tooltip, then click in random cell, then go over
[test--], see the tooltip, it's enough to trigger the button actions and
see the result cell changing....So obviously putting the mouse over a
button is enough to trigger the action.

As you can guess, my spreadsheet has more buttons, and I have some very
funny behavior (version 1.1): even when I don't click in a button, or go
over it, it triggers the button action, because the result cells are
updated! that is the weirdest thing...it's not systematic, but it happens
on a regular basis. So basically I cannot rely on buttons to do what I
want. I'm going to try to display some dialogs with buttons and see how it
goes, I will keep you posted. I am also thinking of hacking pyspread and
add a specific toolbar for my application if it's not too difficult to do,
but it's a route I'd rather not take.

Thanks for the support,
Faycal



On Tue, Jun 14, 2016 at 9:24 AM, Martin Manns <notifications@github.com>
wrote:

> I have not been able to reproduce the exact behavior on Debian Linux
> (unstable) using pyspread 1.0.3 with wx version 3.0.2.0 gtk2 (classic) with
> the attached zipped test file buttontest.zip
> <https://github.com/manns/pyspread/files/312931/buttontest.zip>.
>
> I found the following glitches though:
>
>    - When the mouse stops over the button before first execution then a
>    tooltip is generated that shows the cell result. This tooltip causes the
>    button cell to be executed. I have disabled tooltips for button cells and
>    frozen cells in the 1.1 branch.
>    - The former behavior should also occur if the cell cache is exceeded,
>    i.e. if many thousand cells are filled in the spreadsheet. Then the tooltip
>    may again execute the button cell code.
>    - Double clicks are interpreted as single clicks by the button cell. I
>    doubt that this is a practical issue.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/manns/pyspread/issues/133#issuecomment-225747717>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AF486E4Rienv8XBjUCo2HL4qZ7gioJQhks5qLfS-gaJpZM4IwndF>
> .
>



-- 
<table style="font-size:11px;color:#555;border-collapse:collapse;">
<tr>
<td><img src="http://img150.imageshack.us/img150/3300/gmailphplc3.th.png"
alt="fayce66@gmail.com" /></td>
</tr>
</table>

**Comment by fayce66** [comment]
here is the modified buttontest...

On Tue, Jun 14, 2016 at 1:52 PM, Fayce <fayce66@gmail.com> wrote:

> Hi Martin,
>
> I tried your buttontest file with version 1.1 and I have the following
> issues:
> - when the tooltip appears, and I click in another cell, the button code
> get executed and the result cell is updated.
> - sometimes when I click just once in the button (coming from another
> cell), nothing happens (i.e the result cell is not executed), but it seems
> that sometimes clicking away triggers the button macro and the result cell
> is updated. It's not systematic, maybe clicking once trigger the tooltip
> but it's not displayed on the screen)
> - I renamed your button [test++] and I added a button [test--] with
> "i=i-1". Now this is interesting:
>     a/ the first time I restarted the spreadsheet, the result cell i=0.
> When I clicked in a random cell (not the buttons), the [test--] button was
> triggered and the result cell i displayed -1. After that, restarting the
> spreadsheet did not trigger any action and the result cell was still 0.
>     b/ without EVER clicking in any of the buttons, I just put my mouse
> over [test++], see the tooltip, then click in random cell, then go over
> [test--], see the tooltip, it's enough to trigger the button actions and
> see the result cell changing....So obviously putting the mouse over a
> button is enough to trigger the action.
>
> As you can guess, my spreadsheet has more buttons, and I have some very
> funny behavior (version 1.1): even when I don't click in a button, or go
> over it, it triggers the button action, because the result cells are
> updated! that is the weirdest thing...it's not systematic, but it happens
> on a regular basis. So basically I cannot rely on buttons to do what I
> want. I'm going to try to display some dialogs with buttons and see how it
> goes, I will keep you posted. I am also thinking of hacking pyspread and
> add a specific toolbar for my application if it's not too difficult to do,
> but it's a route I'd rather not take.
>
> Thanks for the support,
> Faycal
>
>
>
> On Tue, Jun 14, 2016 at 9:24 AM, Martin Manns <notifications@github.com>
> wrote:
>
>> I have not been able to reproduce the exact behavior on Debian Linux
>> (unstable) using pyspread 1.0.3 with wx version 3.0.2.0 gtk2 (classic) with
>> the attached zipped test file buttontest.zip
>> <https://github.com/manns/pyspread/files/312931/buttontest.zip>.
>>
>> I found the following glitches though:
>>
>>    - When the mouse stops over the button before first execution then a
>>    tooltip is generated that shows the cell result. This tooltip causes the
>>    button cell to be executed. I have disabled tooltips for button cells and
>>    frozen cells in the 1.1 branch.
>>    - The former behavior should also occur if the cell cache is
>>    exceeded, i.e. if many thousand cells are filled in the spreadsheet. Then
>>    the tooltip may again execute the button cell code.
>>    - Double clicks are interpreted as single clicks by the button cell.
>>    I doubt that this is a practical issue.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/manns/pyspread/issues/133#issuecomment-225747717>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AF486E4Rienv8XBjUCo2HL4qZ7gioJQhks5qLfS-gaJpZM4IwndF>
>> .
>>
>
>
>
> --
> <table style="font-size:11px;color:#555;border-collapse:collapse;">
> <tr>
> <td><img src="http://img150.imageshack.us/img150/3300/gmailphplc3.th.png"
> alt="fayce66@gmail.com" /></td>
> </tr>
> </table>
>



-- 
<table style="font-size:11px;color:#555;border-collapse:collapse;">
<tr>
<td><img src="http://img150.imageshack.us/img150/3300/gmailphplc3.th.png"
alt="fayce66@gmail.com" /></td>
</tr>
</table>

**Comment by manns** [comment]
On Mon, 13 Jun 2016 21:57:18 -0700
Fayce <notifications@github.com> wrote:

> here is the modified buttontest...

I cannot download it.

**Comment by manns** [comment]
I try my best but with the 1.1 branch version, I never get a tooltip when the mouse is over the button. Did you clone from github and did you checkout the 1.1 branch instead of master?

**Comment by fayce66** [comment]
I went to *https://github.com/manns/pyspread/tree/1.1
<https://github.com/manns/pyspread/tree/1.1>* then selected branch:1.1 then
clicked on [clone or download] button to download the gz file.

I did the install in /usr/local/ in my linux desktop:

*faycal@xhugo1:~$ which pyspread*
*/usr/local/bin/pyspread*
*faycal@xhugo1:~$ pyspread --version*
*pyspread 1.1*

I believe when you say there is nothing wrong in your version, obvisouly
there's something wrong in my environment, I checked the wx library:

faycal@xhugo1:~$ dpkg -l | grep wx
rc  libwxbase2.8-0:amd64                        2.8.12.1+dfsg-2ubuntu2
                amd64        wxBase library (runtime) - non-GUI support
classes of wxWidgets toolkit
ii  libwxbase3.0-0v5:amd64                      3.0.2+dfsg-1.3
                amd64        wxBase library (runtime) - non-GUI support
classes of wxWidgets toolkit
rc  libwxgtk-media2.8-0:amd64                   2.8.12.1+dfsg-2ubuntu2
                amd64        wxWidgets Cross-platform C++ GUI toolkit (GTK+
media library runtime)
rc  libwxgtk2.8-0:amd64                         2.8.12.1+dfsg-2ubuntu2
                amd64        wxWidgets Cross-platform C++ GUI toolkit (GTK+
runtime)
ii  libwxgtk3.0-0v5:amd64                       3.0.2+dfsg-1.3
                amd64        wxWidgets Cross-platform C++ GUI toolkit (GTK+
runtime)
ii  python-wxgtk3.0                             3.0.2.0+dfsg-1build1
                amd64        Python interface to the wxWidgets
Cross-platform C++ GUI toolkit
ii  python-wxversion                            3.0.2.0+dfsg-1build1
                all          API for selecting the wxPython version to use

also FYI, I am using python 2.7 (not 3)

I don't see what can be a problem, this is really weird.

Anyway I will wait for your full release of v1.1. In the meantime I will
work on jupyter notebook.

Thanks for your time and support,
Faycal


On Wed, Jun 15, 2016 at 6:28 AM, Martin Manns <notifications@github.com>
wrote:

> I try my best but with the 1.1 branch version, I never get a tooltip when
> the mouse is over the button. Did you clone from github and did you
> checkout the 1.1 branch instead of master?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/manns/pyspread/issues/133#issuecomment-226021907>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AF486MF31Vv8MwCFl1OCDQwLMASPuuNBks5qLx0BgaJpZM4IwndF>
> .
>



-- 
<table style="font-size:11px;color:#555;border-collapse:collapse;">
<tr>
<td><img src="http://img150.imageshack.us/img150/3300/gmailphplc3.th.png"
alt="fayce66@gmail.com" /></td>
</tr>
</table>

**Comment by fayce66** [comment]
Here in attachment is the dependencies screen from pyspread...

On Wed, Jun 15, 2016 at 9:47 AM, Fayce <fayce66@gmail.com> wrote:

> I went to *https://github.com/manns/pyspread/tree/1.1
> <https://github.com/manns/pyspread/tree/1.1>* then selected branch:1.1
> then clicked on [clone or download] button to download the gz file.
>
> I did the install in /usr/local/ in my linux desktop:
>
> *faycal@xhugo1:~$ which pyspread*
> */usr/local/bin/pyspread*
> *faycal@xhugo1:~$ pyspread --version*
> *pyspread 1.1*
>
> I believe when you say there is nothing wrong in your version, obvisouly
> there's something wrong in my environment, I checked the wx library:
>
> faycal@xhugo1:~$ dpkg -l | grep wx
> rc  libwxbase2.8-0:amd64                        2.8.12.1+dfsg-2ubuntu2
>                 amd64        wxBase library (runtime) - non-GUI support
> classes of wxWidgets toolkit
> ii  libwxbase3.0-0v5:amd64                      3.0.2+dfsg-1.3
>                 amd64        wxBase library (runtime) - non-GUI support
> classes of wxWidgets toolkit
> rc  libwxgtk-media2.8-0:amd64                   2.8.12.1+dfsg-2ubuntu2
>                 amd64        wxWidgets Cross-platform C++ GUI toolkit (GTK+
> media library runtime)
> rc  libwxgtk2.8-0:amd64                         2.8.12.1+dfsg-2ubuntu2
>                 amd64        wxWidgets Cross-platform C++ GUI toolkit (GTK+
> runtime)
> ii  libwxgtk3.0-0v5:amd64                       3.0.2+dfsg-1.3
>                 amd64        wxWidgets Cross-platform C++ GUI toolkit (GTK+
> runtime)
> ii  python-wxgtk3.0                             3.0.2.0+dfsg-1build1
>                 amd64        Python interface to the wxWidgets
> Cross-platform C++ GUI toolkit
> ii  python-wxversion                            3.0.2.0+dfsg-1build1
>                 all          API for selecting the wxPython version to use
>
> also FYI, I am using python 2.7 (not 3)
>
> I don't see what can be a problem, this is really weird.
>
> Anyway I will wait for your full release of v1.1. In the meantime I will
> work on jupyter notebook.
>
> Thanks for your time and support,
> Faycal
>
>
> On Wed, Jun 15, 2016 at 6:28 AM, Martin Manns <notifications@github.com>
> wrote:
>
>> I try my best but with the 1.1 branch version, I never get a tooltip when
>> the mouse is over the button. Did you clone from github and did you
>> checkout the 1.1 branch instead of master?
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/manns/pyspread/issues/133#issuecomment-226021907>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AF486MF31Vv8MwCFl1OCDQwLMASPuuNBks5qLx0BgaJpZM4IwndF>
>> .
>>
>
>
>
> --
> <table style="font-size:11px;color:#555;border-collapse:collapse;">
> <tr>
> <td><img src="http://img150.imageshack.us/img150/3300/gmailphplc3.th.png"
> alt="fayce66@gmail.com" /></td>
> </tr>
> </table>
>



-- 
<table style="font-size:11px;color:#555;border-collapse:collapse;">
<tr>
<td><img src="http://img150.imageshack.us/img150/3300/gmailphplc3.th.png"
alt="fayce66@gmail.com" /></td>
</tr>
</table>

**Comment by fayce66** [comment]
Hi Martin,

I checked my packages and it seems that I installed pyspread 1.0.1 from
ubuntu repository the first time I tried pyspread.

I removed the package and now your buttontest example works fine when I run
it (no tooltip). I added an extra button i=i-1 and everything works fine
now.

I then tried my spreadsheet, hoping that everything would be fine, but I
still have some 'funny behavior' for the buttons, like after 2 or more
clicks on a button, the last click does not refresh the cells (as if the
button macro was not executed, or one 'refresh' is missing). The cells are
refreshed only after I click in another empty cell or do 'save'. I will
quick looking at my environment to see if this is not caused by another
package conflict, and will keep you posted...

Thanks for the support,
Faycal


On Wed, Jun 15, 2016 at 9:54 AM, Fayce <fayce66@gmail.com> wrote:

> Here in attachment is the dependencies screen from pyspread...
>
> On Wed, Jun 15, 2016 at 9:47 AM, Fayce <fayce66@gmail.com> wrote:
>
>> I went to *https://github.com/manns/pyspread/tree/1.1
>> <https://github.com/manns/pyspread/tree/1.1>* then selected branch:1.1
>> then clicked on [clone or download] button to download the gz file.
>>
>> I did the install in /usr/local/ in my linux desktop:
>>
>> *faycal@xhugo1:~$ which pyspread*
>> */usr/local/bin/pyspread*
>> *faycal@xhugo1:~$ pyspread --version*
>> *pyspread 1.1*
>>
>> I believe when you say there is nothing wrong in your version, obvisouly
>> there's something wrong in my environment, I checked the wx library:
>>
>> faycal@xhugo1:~$ dpkg -l | grep wx
>> rc  libwxbase2.8-0:amd64                        2.8.12.1+dfsg-2ubuntu2
>>                   amd64        wxBase library (runtime) - non-GUI support
>> classes of wxWidgets toolkit
>> ii  libwxbase3.0-0v5:amd64                      3.0.2+dfsg-1.3
>>                   amd64        wxBase library (runtime) - non-GUI support
>> classes of wxWidgets toolkit
>> rc  libwxgtk-media2.8-0:amd64                   2.8.12.1+dfsg-2ubuntu2
>>                   amd64        wxWidgets Cross-platform C++ GUI toolkit
>> (GTK+ media library runtime)
>> rc  libwxgtk2.8-0:amd64                         2.8.12.1+dfsg-2ubuntu2
>>                   amd64        wxWidgets Cross-platform C++ GUI toolkit
>> (GTK+ runtime)
>> ii  libwxgtk3.0-0v5:amd64                       3.0.2+dfsg-1.3
>>                   amd64        wxWidgets Cross-platform C++ GUI toolkit
>> (GTK+ runtime)
>> ii  python-wxgtk3.0                             3.0.2.0+dfsg-1build1
>>                   amd64        Python interface to the wxWidgets
>> Cross-platform C++ GUI toolkit
>> ii  python-wxversion                            3.0.2.0+dfsg-1build1
>>                   all          API for selecting the wxPython version to use
>>
>> also FYI, I am using python 2.7 (not 3)
>>
>> I don't see what can be a problem, this is really weird.
>>
>> Anyway I will wait for your full release of v1.1. In the meantime I will
>> work on jupyter notebook.
>>
>> Thanks for your time and support,
>> Faycal
>>
>>
>> On Wed, Jun 15, 2016 at 6:28 AM, Martin Manns <notifications@github.com>
>> wrote:
>>
>>> I try my best but with the 1.1 branch version, I never get a tooltip
>>> when the mouse is over the button. Did you clone from github and did you
>>> checkout the 1.1 branch instead of master?
>>>
>>> —
>>> You are receiving this because you authored the thread.
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/manns/pyspread/issues/133#issuecomment-226021907>,
>>> or mute the thread
>>> <https://github.com/notifications/unsubscribe/AF486MF31Vv8MwCFl1OCDQwLMASPuuNBks5qLx0BgaJpZM4IwndF>
>>> .
>>>
>>
>>
>>
>> --
>> <table style="font-size:11px;color:#555;border-collapse:collapse;">
>> <tr>
>> <td><img src="http://img150.imageshack.us/img150/3300/gmailphplc3.th.png"
>> alt="fayce66@gmail.com" /></td>
>> </tr>
>> </table>
>>
>
>
>
> --
> <table style="font-size:11px;color:#555;border-collapse:collapse;">
> <tr>
> <td><img src="http://img150.imageshack.us/img150/3300/gmailphplc3.th.png"
> alt="fayce66@gmail.com" /></td>
> </tr>
> </table>
>



-- 
<table style="font-size:11px;color:#555;border-collapse:collapse;">
<tr>
<td><img src="http://img150.imageshack.us/img150/3300/gmailphplc3.th.png"
alt="fayce66@gmail.com" /></td>
</tr>
</table>

**Comment by manns** [comment]
On Tue, 14 Jun 2016 17:47:26 -0700
Fayce <notifications@github.com> wrote:

> faycal@xhugo1:~$ dpkg -l | grep wx
> rc  libwxbase2.8-0:amd64                        2.8.12.1+dfsg-2ubuntu2
>                 amd64        wxBase library (runtime) - non-GUI
> support classes of wxWidgets toolkit
> ii  libwxbase3.0-0v5:amd64                      3.0.2+dfsg-1.3
>                 amd64        wxBase library (runtime) - non-GUI
> support classes of wxWidgets toolkit
> rc  libwxgtk-media2.8-0:amd64                   2.8.12.1+dfsg-2ubuntu2
>                 amd64        wxWidgets Cross-platform C++ GUI toolkit
> (GTK+ media library runtime)
> rc  libwxgtk2.8-0:amd64                         2.8.12.1+dfsg-2ubuntu2
>                 amd64        wxWidgets Cross-platform C++ GUI toolkit
> (GTK+ runtime)
> ii  libwxgtk3.0-0v5:amd64                       3.0.2+dfsg-1.3
>                 amd64        wxWidgets Cross-platform C++ GUI toolkit
> (GTK+ runtime)
> ii  python-wxgtk3.0                             3.0.2.0+dfsg-1build1
>                 amd64        Python interface to the wxWidgets
> Cross-platform C++ GUI toolkit
> ii  python-wxversion                            3.0.2.0+dfsg-1build1
>                 all          API for selecting the wxPython version
> to use

just for your information:

$ dpkg -l | grep wx
ii  libwxbase3.0-0v5:amd64
3.0.2+dfsg-1.4                       amd64        wxBase library
(runtime) - non-GUI support classes of wxWidgets toolkit ii
libwxgtk-media3.0-0v5:amd64
3.0.2+dfsg-1.4                       amd64        wxWidgets
Cross-platform C++ GUI toolkit (GTK+ media library runtime) ii
libwxgtk3.0-0v5:amd64
3.0.2+dfsg-1.4                       amd64        wxWidgets
Cross-platform C++ GUI toolkit (GTK+ runtime) ii
python-wxglade
0.7.1~rc1-3                          all          GUI designer written
in Python with wxPython ii  python-wxgtk-media3.0
3.0.2.0+dfsg-2                       amd64        Python interface to
the wxWidgets Cross-platform C++ GUI toolkit (wx.media) ii
python-wxgtk3.0
3.0.2.0+dfsg-2                       amd64        Python interface to
the wxWidgets Cross-platform C++ GUI toolkit ii
python-wxmpl
2.0.0-2.1                            all          Painless matplotlib
embedding in wxPython rc  python-wxtools
3.0.2.0+dfsg-1                       all          Tools from the
wxPython distribution ii  python-wxversion
3.0.2.0+dfsg-2                       all          API for selecting the
wxPython version to use

Cheers 

Martin

**Comment by manns** [comment]
On Tue, 14 Jun 2016 17:54:22 -0700
Fayce <notifications@github.com> wrote:

> Here in attachment is the dependencies screen from pyspread...

Sorry, I cannot find any attachment.

I also did not get your version of the misbehaving spreadsheet so I
cannot look into it.

Could you please send both as an e-mail attachment?

Kind Regards

Martin

**Comment by fayce66** [comment]
Hi Martin,

Almost all is well that ends well...I removed all pyspread packages from my
PC, then reinstalled everything by downloading zip file (can't do git as
the https link points to 1.0.3). Buttons behave like they should: 1st click
gives focus, 2nd click triggers actions, and result cells are updated. So
that's perfect on that side. Just a tiny issue remaining: if the button is
on merged cells, the action is executed only if I click in the original
cell containing the macro. Clicking on the other merge cells does not
trigger the button action. I even copy/paste the macro in the other cells
before merging but no effect. No big deal as the workaround is just to
click in the top-left cell of the button, and that's it, but I just thought
I let you know.

Thanks for the support,
Regards,
Faycal



On Wed, Jun 15, 2016 at 4:11 PM, Fayce <fayce66@gmail.com> wrote:

> Hi Martin,
>
> I checked my packages and it seems that I installed pyspread 1.0.1 from
> ubuntu repository the first time I tried pyspread.
>
> I removed the package and now your buttontest example works fine when I
> run it (no tooltip). I added an extra button i=i-1 and everything works
> fine now.
>
> I then tried my spreadsheet, hoping that everything would be fine, but I
> still have some 'funny behavior' for the buttons, like after 2 or more
> clicks on a button, the last click does not refresh the cells (as if the
> button macro was not executed, or one 'refresh' is missing). The cells are
> refreshed only after I click in another empty cell or do 'save'. I will
> quick looking at my environment to see if this is not caused by another
> package conflict, and will keep you posted...
>
> Thanks for the support,
> Faycal
>
>
> On Wed, Jun 15, 2016 at 9:54 AM, Fayce <fayce66@gmail.com> wrote:
>
>> Here in attachment is the dependencies screen from pyspread...
>>
>> On Wed, Jun 15, 2016 at 9:47 AM, Fayce <fayce66@gmail.com> wrote:
>>
>>> I went to *https://github.com/manns/pyspread/tree/1.1
>>> <https://github.com/manns/pyspread/tree/1.1>* then selected branch:1.1
>>> then clicked on [clone or download] button to download the gz file.
>>>
>>> I did the install in /usr/local/ in my linux desktop:
>>>
>>> *faycal@xhugo1:~$ which pyspread*
>>> */usr/local/bin/pyspread*
>>> *faycal@xhugo1:~$ pyspread --version*
>>> *pyspread 1.1*
>>>
>>> I believe when you say there is nothing wrong in your version, obvisouly
>>> there's something wrong in my environment, I checked the wx library:
>>>
>>> faycal@xhugo1:~$ dpkg -l | grep wx
>>> rc  libwxbase2.8-0:amd64                        2.8.12.1+dfsg-2ubuntu2
>>>                   amd64        wxBase library (runtime) - non-GUI support
>>> classes of wxWidgets toolkit
>>> ii  libwxbase3.0-0v5:amd64                      3.0.2+dfsg-1.3
>>>                   amd64        wxBase library (runtime) - non-GUI support
>>> classes of wxWidgets toolkit
>>> rc  libwxgtk-media2.8-0:amd64                   2.8.12.1+dfsg-2ubuntu2
>>>                   amd64        wxWidgets Cross-platform C++ GUI toolkit
>>> (GTK+ media library runtime)
>>> rc  libwxgtk2.8-0:amd64                         2.8.12.1+dfsg-2ubuntu2
>>>                   amd64        wxWidgets Cross-platform C++ GUI toolkit
>>> (GTK+ runtime)
>>> ii  libwxgtk3.0-0v5:amd64                       3.0.2+dfsg-1.3
>>>                   amd64        wxWidgets Cross-platform C++ GUI toolkit
>>> (GTK+ runtime)
>>> ii  python-wxgtk3.0                             3.0.2.0+dfsg-1build1
>>>                   amd64        Python interface to the wxWidgets
>>> Cross-platform C++ GUI toolkit
>>> ii  python-wxversion                            3.0.2.0+dfsg-1build1
>>>                   all          API for selecting the wxPython version to use
>>>
>>> also FYI, I am using python 2.7 (not 3)
>>>
>>> I don't see what can be a problem, this is really weird.
>>>
>>> Anyway I will wait for your full release of v1.1. In the meantime I will
>>> work on jupyter notebook.
>>>
>>> Thanks for your time and support,
>>> Faycal
>>>
>>>
>>> On Wed, Jun 15, 2016 at 6:28 AM, Martin Manns <notifications@github.com>
>>> wrote:
>>>
>>>> I try my best but with the 1.1 branch version, I never get a tooltip
>>>> when the mouse is over the button. Did you clone from github and did you
>>>> checkout the 1.1 branch instead of master?
>>>>
>>>> —
>>>> You are receiving this because you authored the thread.
>>>> Reply to this email directly, view it on GitHub
>>>> <https://github.com/manns/pyspread/issues/133#issuecomment-226021907>,
>>>> or mute the thread
>>>> <https://github.com/notifications/unsubscribe/AF486MF31Vv8MwCFl1OCDQwLMASPuuNBks5qLx0BgaJpZM4IwndF>
>>>> .
>>>>
>>>
>>>
>>>
>>> --
>>> <table style="font-size:11px;color:#555;border-collapse:collapse;">
>>> <tr>
>>> <td><img src="http://img150.imageshack.us/img150/3300/gmailphplc3.th.png"
>>> alt="fayce66@gmail.com" /></td>
>>> </tr>
>>> </table>
>>>
>>
>>
>>
>> --
>> <table style="font-size:11px;color:#555;border-collapse:collapse;">
>> <tr>
>> <td><img src="http://img150.imageshack.us/img150/3300/gmailphplc3.th.png"
>> alt="fayce66@gmail.com" /></td>
>> </tr>
>> </table>
>>
>
>
>
> --
> <table style="font-size:11px;color:#555;border-collapse:collapse;">
> <tr>
> <td><img src="http://img150.imageshack.us/img150/3300/gmailphplc3.th.png"
> alt="fayce66@gmail.com" /></td>
> </tr>
> </table>
>



-- 
<table style="font-size:11px;color:#555;border-collapse:collapse;">
<tr>
<td><img src="http://img150.imageshack.us/img150/3300/gmailphplc3.th.png"
alt="fayce66@gmail.com" /></td>
</tr>
</table>

**Comment by fayce66** [comment]
I did attach the spreadsheet but here we go again, just the button test.
only issue remaining is button action in merged cells...cheers

On Fri, Jun 17, 2016 at 3:21 AM, Martin Manns <notifications@github.com>
wrote:

> On Tue, 14 Jun 2016 17:54:22 -0700
> Fayce <notifications@github.com> wrote:
>
> > Here in attachment is the dependencies screen from pyspread...
>
> Sorry, I cannot find any attachment.
>
> I also did not get your version of the misbehaving spreadsheet so I
> cannot look into it.
>
> Could you please send both as an e-mail attachment?
>
> Kind Regards
>
>
> Martin
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/manns/pyspread/issues/133#issuecomment-226570000>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AF486GLxeGid73IRzczewWHQsvWl-55vks5qMZQegaJpZM4IwndF>
> .
>



-- 
<table style="font-size:11px;color:#555;border-collapse:collapse;">
<tr>
<td><img src="http://img150.imageshack.us/img150/3300/gmailphplc3.th.png"
alt="fayce66@gmail.com" /></td>
</tr>
</table>

**Comment by manns** [comment]
This is the expected behavior. (improvements would be welcome)
I close this issue now.
