### ISSUE TITLE
str literals do not work on OSX with version 1.1

### ISSUE THREAD

**Issue by Yatekii** [manns/pyspread#138]
Putting "STR", nor 'STR' , nor str('STR'), nor ' '.join('STR') into a cell does not work in this version.

It always evaluates to 'invalid syntax (<unknown>,line 1)'.

Defining a = 'STR' in the macros and then evaluating (a) works tho ...

**Comment by manns** [comment]
I cannot reproduce this on Debian.

What about other strings?

**Comment by Yatekii** [comment]
You mean other string-contents? STR was just a placeholder ... can't use any strings ... which is weird because I am sure you use __repr__() or __str__() of the respective object ...

**Comment by manns** [comment]
Do you see any errors when starting pyspread from a shell?

**Comment by Yatekii** [comment]
nope :)

**Comment by manns** [comment]
Just a wild guess:

Did you put 
```
="STR"
```
into the cell?

This yields
```
invalid syntax (<unknown>, line 1)
```
which is correct.

Either you should state
```
s = "STR"
```
or just
```
"STR"
```

**Comment by Yatekii** [comment]
No, I did as I said :) I just put ther string. I also tried putting u"STR" :) All other evals (e.g. 3+4, S[1,2,3]) work fine.

**Comment by manns** [comment]
Sorry for the wrong assumption.

Since you wanted to dig into pyspread anyway:
The relevant code is in  pyspread/pyspread/src/model/model.py

line 1230:
```python
def _eval_cell(self, key, code):
```
with the eval call in line 1313

You could check if the line is reached at all and if yes what parameters are given.

Another cause may be that OS X may handle SIGALRM system signals diiferntly, i.e. the signal checks may be incorrect  for OS X.

Furthermore, it may help to know all your dependencies' versions

**Comment by Yatekii** [comment]
No worries mate, one can only try ;)

I will look into this!

**Comment by Yatekii** [comment]
Ok, the Problem is that " is converted to \u201c (curly one) and same for ' ...
Now the question is: is that a wx or an OSX issue ...

**Comment by Yatekii** [comment]
It was indeed an OSX issue. I was able to disable it for OSX since I don't want that ridiculous feature anyways. IDK how to disable it generally tho. Editors and Excel for example are abloe to correct that somehow too.

**Comment by vovkkk** [comment]
You have to put unicode char in unicode literal like this `u'”‘«»‘’'`.
String literal (or type) cannot contain unicode, only bytes.

**Comment by Yatekii** [comment]
I think you missunderstand :)
The contained object is of type unicode which is correct since curly "' are used.
But the AST just accepts string (ascii) and not unicode. This then ultimately fails.
You cannot change that in any way. Not even by prepending u. The only thing that helps is giving the AST valid code which is not using unicode "' as string literal identifiers ;)
Hope that clarifies it for you ;)

**Comment by vovkkk** [comment]
Uh, yes; then instead of quotes you can use in main menu Edit → Quote cell(s) (<kbd>ctrl+enter</kbd> on Windows), i.e. just type text without quotes and press shortcut to quote it.
