### ISSUE TITLE
When typing into a cell, the entry line lags behind by one character

### ISSUE THREAD

**Issue by mgunyho** [manns/pyspread#145]
Using Kubuntu 17.04. Best explained with a gif:
![delay1](https://user-images.githubusercontent.com/20118130/28502932-80211a9a-7005-11e7-96ad-47900a15d280.gif)
The cell contents are updated correctly when pressing enter, so this is only a visual bug. Still somewhat confusing.

Also, if I start typing into the entry line, the cell doesn't get updated at all until pressing enter. Is this intentional? Other spreadsheet programs update both the cell and entry line simultaneously either way.

**Comment by manns** [comment]
Reproduced with Debian sid

**Comment by manns** [comment]
Please check if this is fixed in the master branch.

**Comment by mgunyho** [comment]
Yes, it works now. The way it's done with OnKeyUp makes it feel maybe slightly "sticky" but definitely much better.
