### ISSUE TITLE
Feature request: please add support for formatting/inserting hyperlinks in text

### ISSUE THREAD

**Issue by sdaau** [manns/pyspread#150]
Pyspread can have a cell formatted as Pango markup, in which case a limited subset of HTML is supported (https://developer.gnome.org/pango/stable/PangoMarkupFormat.html). Unfortunately, Pango does not support the anchor tag `<a href="...">link text</a>`

Would it be possible to somehow allow support for hyperlinks? Ideally, it would work like in Libre/OpenOffice (select a piece of text in cell, choose Insert Hyperlink, add the link in the dialog, then the snippet of text turns into a link); however, just support for the `<a>` tag as part of Pango markup would be great.

Thanks for the great software!

**Comment by manns** [comment]
I understand your request. However, this would require a special high performance parser, essentially extending pango. As soon as cairopango supports this feature, adding the functionality to pyspread would be doable. Writing such a parser from scratch is well beyond the scope of pyspread.

How about using a button cell to launch a Web Browser with the desired link?

**Comment by sdaau** [comment]
Thanks for the reply @manns !

> Writing such a parser from scratch is well beyond the scope of pyspread.

Understandable, I was just hoping there might have been an easier solution (i.e. use some HTML parsing library), but I guess then one would have to put effort to get it to work with GtkCellRenderer, which wouldn't be trivial either...

> As soon as cairopango supports this feature, adding the functionality to pyspread would be doable.

Great, thanks for this - at least it is some sort of a milestone...

> How about using a button cell to launch a Web Browser with the desired link?

That is in principle a good advice; however, why I got very interested in `pyspread`, is that it handles images inside cells easily. And so, what I need to do with a spreadsheet in this case is a shopping list: one column is product name, another product image, and for the third cell, I'd like to enter something like `20$ at <a href="http://www.veeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeerylonglinkfromamazonorebay.com/">[1]</a>, 25$ at <a....` so I have a quick overview of prices, and can quickly link to the required page; using a button would force me to use a separate cell for each link, and would make it less readable for me.

Still, not a big problem - good that at least some need for this feature is documented now,

Thanks again!

**Comment by manns** [comment]
On Wed, 13 Sep 2017 07:45:44 +0000 (UTC)
sdaau <notifications@github.com> wrote:

> > How about using a button cell to launch a Web Browser with the
> > desired link?  
> 
> That is in principle a good advice; however, why I got very
> interested in `pyspread`, is that it handles images inside cells
> easily. And so, what I need to do with a spreadsheet in this case is
> a shopping list: one column is product name, another product image,
> and for the third cell, I'd like to enter something like `20$ at <a
> href="http://www.veeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeerylonglinkfromamazonorebay.com/">[1]</a>,
> 25$ at <a....` so I have a quick overview of prices, and can quickly
> link to the required page; using a button would force me to use a
> separate cell for each link, and would make it less readable for me.

Pyspread can also render svg via rsvg. I am unsure how it handles svg
links though. Have you already tried out a link that is inside an svg?

Kind regards

Martin

**Comment by manns** [comment]
I am not going to fix this soon because I am even unsure if such a hyperlink functionality is desirable or not.
I am going to reconsider if there is a patch available.
