### ISSUE TITLE
Conditional Formatting, Custom Sort?

### ISSUE THREAD

**Issue by JennDahm** [manns/pyspread#152]
Conditional formatting (that is, change the format of a cell based on its content) is a feature in many modern spreadsheet software, but I haven't found it in pyspread. I imagine with full Python expressions available, this would be even more powerful. Custom sort orders would also be great for when I have a field more akin to an enumeration that I'd like to sort in a non-alphabetical order.

Have you considered these features? How difficult would they be to implement? (Alternatively, did I simply miss them in the interface somewhere?)

**Comment by manns** [comment]
Using a macro, conditional formatting can already be achieved (see below). Custom sort keys are not supported but would be easy to implement. 

However, both functionalities are currently missing in the GUI. The main reason is that I have not come up with a workflow that is fast, simple to understand and enjoyable to use. If you have such a concept using stock wxPython widgets please let me know. (Please do not include complex dialog windows.)

Conditional formatting works as follows:

You need to adjust S.cell_attributes for the current cell with a function.

```python
def selfsize(x, y, z, res):
    """Conditionally adjusts font size to res"""

    S.cell_attributes[x, y, z]["pointsize"] = res
    return res
```

When you now put 
```python
selfsize(X, Y, Z, 30) 
```
in any cell, the font of the cell will be resized to 30 points and the cell result is 30.

This works for color, alignment, etc. in a similar way. S.cell_attributes[X, Y, Z] in any cell that is formatted with the conditional format that you want to achieve will tell you the dictionary keys and values that you need to adjust depending on res.

**Comment by JonDahm** [comment]
Thanks for the response! I didn't realize the S variable could be used to change the formatting of the cell, though I might have if I had looked closer. A macro call could work, but you'd have to work it into the expression of every cell you want to format. That wouldn't be too hard if you had the macro simply return a specific argument passed to it. Alternatively, you could have a set of cells dedicated to formatting other cells.

----

I'm not familiar enough with wxPython to suggest the exact widgets to use, so all I can suggest is a UX. This is similar to how other spreadsheet software does it, but as simple as I think I can make it:

When a user has cells selected, they might press a button to bring up a window/dialog that lets them select or create a format style, then specify an expression that will apply the format when true and not apply the format when false. The window might also support creating multiple conditional formats or show existing conditional formats.

As for implementation, there would likely need to be a macro to apply the formatting with three parameters: the format, the conditional expression, and the value of the cell to be formatted. From here, there are a couple of options.

1. Modify the cell's value itself by wrapping its expression with a call to this macro. This is a little messy, but doesn't require anything too special.

2. Create a separate, "hidden" sheet for each sheet with conditional formatting. By "hidden" I mean not accessible by other cells and not assigned a Z value - it's important to display the expression to the user, but I don't think other cells need to access the conditional formatting code. This also gives the benefit of more cleanly separating cell formatting from values.

----

Now that I know that there is at least a way to conditionally format cells using macros, I'm not so much in need of a GUI workflow. Custom sorting would be nice though.

I'll look further into how you might create a UI dialog to create custom sort orders. I don't have a lot of examples that I've encountered to draw from.

Don't take any of this as a demand, by the way. These aren't make-or-break features, just nice-to-haves. :)

**Comment by manns** [comment]
Pyspread tries not to hide anything. Therefore, (1) is preferable.

I have generalized the functionality. Therefore the macro is
```python
def conditional_format(res, x, y, z, cond, format, default_format=None):
	"""Conditional cell formatter"""

	default_cell_attributes = \
		copy(S.cell_attributes.default_cell_attributes)

	if cond(res):
		S.cell_attributes[x, y, z].update(format)
	else:
		if default_format is None:
			default_format = default_cell_attributes

		S.cell_attributes[x, y, z].update(default_format)

	return res
```

The cell code would be e.g.:
```python
conditional_format(40, X, Y, Z, lambda r: r > 10, {'bgcolor': 32768})
```
which I still consider a bit messy.

I could imagine a workflow, in which the user formats the cell as in highlighted mode and then runs the macro via the menu. The macro asks for the condition and creates the cell code. This would be easy to implement.

It would be much harder to modify this macro using a user interface. Therefore, a robust cell code parser would be needed similar to the chart_dialog.

**Comment by manns** [comment]
This will not be realized in the Python2 branch.
Therefore, I am closing the issue.

**Comment by pedromorgan** [comment]
https://gitter.im/pyspread/community
