### ISSUE TITLE
Pyqt/PySide Port

### ISSUE THREAD

**Issue by ruchitinfushion** [manns/pyspread#153]
Hi folks,
Any plan to integrate Qt (PyQt/Pyside) library for GUI & graphics ? Qt is fast, user-friendly, opensource, cross platform,  support,etc.

**Comment by manns** [comment]
The decision for wxPython and against PyQt had been made in 2008.
Reasons were the free license (does not apply anymore) and the wx.Grid widget that is obviously a central component of pyspread. Furthermore, the cross-platform native widget support of wx was a plus.

Currently, the bugs from the transition from classical wxPython to wxPython Phoenix is stalling the Python3 port for the last few years (see issue #137).  However, as soon as the pango font issue in GTK is solved, the port to Phoenix should be much easier than a port to PyQt.

Therefore, the current plan is to stick to wx.
