### ISSUE TITLE
can we import data from sqlite3 into pyspread?

### ISSUE THREAD

**Issue by TarzanWonder** [manns/pyspread#154]

**Comment by manns** [comment]
This should work with a small macro.

**Comment by TarzanWonder** [comment]
If I have to create redistributable package of it using pyinstaller,will it work?

**Comment by manns** [comment]
If you intend to package pyspread with pyinstaller I would very much appreciate it.

I only have created a package using distutils and py2exe, yet.
Therefore, I cannot really tell if you may run into issues with pyinstaller or not.
