### ISSUE TITLE
'WindowsError' is not defined

### ISSUE THREAD

**Issue by rudolfII** [manns/pyspread#155]
Trying to run on OpenBSD, I get:

$ pyspread                                                                 
Traceback (most recent call last):
  File "/usr/local/bin/pyspread", line 243, in <module>
    pyspread()
  File "/usr/local/bin/pyspread", line 229, in pyspread
    app = MainApplication(S=S, redirect=False)
  File "/usr/local/bin/pyspread", line 172, in __init__
    wx.App.__init__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/wx/_core.py", line 7981, in __init__
    self._BootstrapApp()
  File "/usr/local/lib/python2.7/site-packages/wx/_core.py", line 7555, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "/usr/local/bin/pyspread", line 191, in OnInit
    from src.gui._main_window import MainWindow
  File "/usr/local/lib/python2.7/site-packages/pyspread/src/gui/_main_window.py", line 67, in <module>
    from src.gui._grid import Grid
  File "/usr/local/lib/python2.7/site-packages/pyspread/src/gui/_grid.py", line 45, in <module>
    from _grid_renderer import GridRenderer, RowLabelRenderer, ColLabelRenderer
  File "/usr/local/lib/python2.7/site-packages/pyspread/src/gui/_grid_renderer.py", line 46, in <module>
    except (ImportError, WindowsError):
NameError: name 'WindowsError' is not defined

Ruda

**Comment by manns** [comment]
Could you please specify your python version?

Furthermore, do you still get an error if you change line 46 in "/usr/local/lib/python2.7/site-packages/pyspread/src/gui/_grid_renderer.py" to 
```python
except ImportError:

**Comment by rudolfII** [comment]
On Tue, 16 Oct 2018 at 19:13, Martin Manns <notifications@github.com> wrote:

> Could you please specify your python version?
>

  $python2
Python 2.7.15 (default, Oct  1 2018, 09:48:49)
[GCC 4.2.1 Compatible OpenBSD Clang 6.0.0 (tags/RELEASE_600/final)] on
openbsd6


> Furthermore, do you still get an error if you change line 46 in
> "/usr/local/lib/python2.7/site-packages/pyspread/src/gui/_grid_renderer.py"
> to
>
> except ImportError:
>
>
Now there is:
So you say openbsd not supported...

  $pyspread
Traceback (most recent call last):
  File "/usr/local/bin/pyspread", line 243, in <module>
    pyspread()
  File "/usr/local/bin/pyspread", line 229, in pyspread
    app = MainApplication(S=S, redirect=False)
  File "/usr/local/bin/pyspread", line 172, in __init__
    wx.App.__init__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/wx/_core.py", line 7981, in
__init__
    self._BootstrapApp()
  File "/usr/local/lib/python2.7/site-packages/wx/_core.py", line 7555, in
_BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "/usr/local/bin/pyspread", line 191, in OnInit
    from src.gui._main_window import MainWindow
  File
"/usr/local/lib/python2.7/site-packages/pyspread/src/gui/_main_window.py",
line 67, in <module>
    from src.gui._grid import Grid
  File "/usr/local/lib/python2.7/site-packages/pyspread/src/gui/_grid.py",
line 45, in <module>
    from _grid_renderer import GridRenderer, RowLabelRenderer,
ColLabelRenderer
  File
"/usr/local/lib/python2.7/site-packages/pyspread/src/gui/_grid_renderer.py",
line 44, in <module>
    import src.lib.vlc as vlc
  File "/usr/local/lib/python2.7/site-packages/pyspread/src/lib/vlc.py",
line 168, in <module>
    dll, plugin_path  = find_lib()
  File "/usr/local/lib/python2.7/site-packages/pyspread/src/lib/vlc.py",
line 163, in find_lib
    raise NotImplementedError('%s: %s not supported' % (sys.argv[0],
sys.platform))
NotImplementedError: /usr/local/bin/pyspread: openbsd6 not supported


Thanks
Ruda

**Comment by manns** [comment]
It seems that I have to catch errors dfferently on OpenBSD because of 3rd party libraries such as libvlc.
I have not been aware of this.

Let me prepare a fix.

**Comment by manns** [comment]
Please reopen this issue if the problem still shows up.

**Comment by intuited** [comment]
Hi, I'm getting the same error (as the initial post) on MacOS 10.13 High Sierra.

After making [the change you suggest](https://github.com/manns/pyspread/issues/155#issuecomment-430320146) to line 46, I get the following error

> /usr/local/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_core.py:16633: UserWarning: wxPython/wxWidgets release number mismatch
>   warnings.warn("wxPython/wxWidgets release number mismatch")
> Traceback (most recent call last):
>   File "/usr/local/bin/pyspread", line 243, in <module>
>     pyspread()
>   File "/usr/local/bin/pyspread", line 229, in pyspread
>     app = MainApplication(S=S, redirect=False)
>   File "/usr/local/bin/pyspread", line 172, in __init__
>     wx.App.__init__(self, *args, **kwargs)
>   File "/usr/local/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_core.py", line 8628, in __init__
>     self._BootstrapApp()
>   File "/usr/local/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_core.py", line 8196, in _BootstrapApp
>     return _core_.PyApp__BootstrapApp(*args, **kwargs)
>   File "/usr/local/bin/pyspread", line 191, in OnInit
>     from src.gui._main_window import MainWindow
>   File "/usr/local/lib/python2.7/site-packages/pyspread/src/gui/_main_window.py", line 67, in <module>
>     from src.gui._grid import Grid
>   File "/usr/local/lib/python2.7/site-packages/pyspread/src/gui/_grid.py", line 45, in <module>
>     from _grid_renderer import GridRenderer, RowLabelRenderer, ColLabelRenderer
>   File "/usr/local/lib/python2.7/site-packages/pyspread/src/gui/_grid_renderer.py", line 44, in <module>
>     import src.lib.vlc as vlc
>   File "/usr/local/lib/python2.7/site-packages/pyspread/src/lib/vlc.py", line 168, in <module>
>     dll, plugin_path  = find_lib()
>   File "/usr/local/lib/python2.7/site-packages/pyspread/src/lib/vlc.py", line 155, in find_lib
>     dll = ctypes.CDLL(p)
>   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 366, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: dlopen(/Applications/VLC.app/Contents/MacOS/lib/libvlc.dylib, 6): Library not loaded: @rpath/libvlccore.dylib
>   Referenced from: /Applications/VLC.app/Contents/MacOS/lib/libvlc.dylib
>   Reason: image not found

I have installed the `python-vlc` package through pip; attempts to install the `vlc` package gave a bunch of errors.  If it seems relevant I can post them.  I do have VLC 3.0.4 installed via download and it seems to work properly.

**Comment by manns** [comment]
@intuited 
Ok, OSX seems to throw an OS error.
I now catch them all because the vlc guys seem to throw all kinds of areas for different platforms.

**Comment by manns** [comment]
Since I have not got any feedback of the problem still being there, I am closing the issue.
