### ISSUE TITLE
ImportError: No module named sysvars (FreeBSD)

### ISSUE THREAD

**Issue by nunotexbsd** [manns/pyspread#157]
Hello,

Trying to run pyspread on FreeBSD 12.0 directly from source since there is no port yet in FreeBSD.

What I've installed from ports as requerements:
(python27-2.7.15)
py27-numpy-1.16.1,1
py27-wxPython28-2.8.12.1_11
py27-matplotlib-2.1.2_5
py27-cairo-1.14.1
py27-python-gnupg-0.4.3

( www.freshports.org for info about this pkgs/ports)

-> pwd: ~/WORK/pyspread-1.1.3/pyspread
-> python2.7 pyspread

I got this error:

Traceback (most recent call last):
  File "pyspread", line 46, in <module>
    from sysvars import get_program_path
ImportError: No module named sysvars

I presume that this is something related to gnupg that I have already installed:

gnupg-2.2.13

Thanks,

Nuno Teixeira

**Comment by manns** [comment]
The error message means that the folder pyspread/src, where the file sysvars.py is located, is not in your PATH or PYTHONPATH.
Have you already tried out the script pyspread.sh to run pyspread?

**Comment by nunotexbsd** [comment]
Hello,

I set PYTHONPATH to src and now I'm getting some errors about dependencies:

Traceback (most recent call last):
  File "pyspread", line 248, in <module>
    pyspread()
  File "pyspread", line 234, in pyspread
    app = MainApplication(S=S, redirect=False)
  File "pyspread", line 177, in __init__
    wx.App.__init__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 7981, in __init__
    self._BootstrapApp()
  File "/usr/local/lib/python2.7/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 7555, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "pyspread", line 196, in OnInit
    from src.gui._main_window import MainWindow
  File "/usr/home/nunotex/WORK/pyspread-1.1.3/pyspread/src/gui/_main_window.py", line 72, in <module>
    from src.gui._grid import Grid
  File "/usr/home/nunotex/WORK/pyspread-1.1.3/pyspread/src/gui/_grid.py", line 45, in <module>
    from _grid_renderer import GridRenderer, RowLabelRenderer, ColLabelRenderer
  File "/usr/home/nunotex/WORK/pyspread-1.1.3/pyspread/src/gui/_grid_renderer.py", line 40, in <module>
    from src.lib._grid_cairo_renderer import GridCellCairoRenderer
  File "/usr/home/nunotex/WORK/pyspread-1.1.3/pyspread/src/lib/_grid_cairo_renderer.py", line 43, in <module>
    import numpy
  File "/usr/local/lib/python2.7/site-packages/numpy/__init__.py", line 140, in <module>
    from . import _distributor_init
ImportError: cannot import name _distributor_init

Thanks,

Nuno Teixeira

**Comment by manns** [comment]
Hi

it seems that your numpy installation has issues.
Does importing numpy from a Python shell work (see below)?
```
~$ python2.7
Python 2.7.16rc1 (default, Feb 18 2019, 11:05:09) 
[GCC 8.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> 
```

Martin

**Comment by nunotexbsd** [comment]
Hi,

I did import numpy with no errors.

In help "modules" shows numpy in the list and if I run:

help> modules numpy

Here is a list of matching modules.  Enter any module name to get more help.

No handlers could be found for logger "OpenGL.Tk"
OpenGL.arrays.numpybuffers - Buffer based Numpy plugin (not used)
OpenGL.arrays.numpymodule - Numpy (new version) module implementation of the OpenGL-ctypes array interfaces
numpy - NumPy
numpy.__config__
numpy._distributor_init - Distributor init file
numpy._globals - Module defining global singleton classes.
numpy._pytesttester - Pytest test running.
numpy.compat - Compatibility module.
numpy.compat._inspect - Subset of inspect module from upstream python
numpy.compat.py3k - Python 3 compatibility tools.
numpy.compat.setup
numpy.compat.tests
...

Thanks,

Nuno

**Comment by manns** [comment]
Unfortunately, I am not familiar with FreeBSD's intrinsics.

However, the error shows up at initial numpy import in pyspread.
Following the error messages, Python fails to find a _distributor_init.py file at the path /usr/local/lib/python2.7/site-packages/numpy/ or it fails importing this file somehow.

When I read the following link, I assume it could be a distributor issue from the ports:
https://stackoverflow.com/questions/48423782/importerror-cannot-import-name-distributor-init

From my point of view, there are two ways to go:
1) Try to create the missing file with #!/usr/bin/env python in the first line. If successful report a bug to freshports.
2) Try installing another numpy distribution e.g. via pip.

**Comment by micheal-hill** [comment]
I'm seeing this same error with pyspread in Fedora too, installed from system repository:
```
Name         : pyspread
Version      : 1.1.2
Release      : 4.1
Architecture : noarch
Size         : 27 M
Source       : pyspread-1.1.2-4.1.src.rpm
Repository   : @System
From repo    : rpmsphere-noarch
Summary      : Cross-platform Python spreadsheet application
URL          : http://manns.github.io/pyspread/
```

**Comment by manns** [comment]
@micheal-hill If you refer to the initial post, have you tried starting pyspread with the script pyspread.sh? To what file does /usr/bin/pyspread link in Fedora's rpm package?

**Comment by manns** [comment]
I assume that the problem has been fixed.
