### ISSUE TITLE
Python3: Leaving fullscreen unmaximizes window

### ISSUE THREAD

**Issue by manns** [manns/pyspread#161]
When leaving fullscreen mode in the Python3 version, a previously maximized window appears unmaximized.
I am using Debian unstable with the Mate desktop manager.

@pedromorgan I have reviewed your fullscreen code and cannot find the issue

**Comment by pedromorgan** [comment]
strange.. works fine here on xubuntu/xfce with dual screens.

**Comment by manns** [comment]
Maybe it is a Mate issue. I will close this one for now.
