### ISSUE TITLE
[python3] support different engines

### ISSUE THREAD

**Issue by pedromorgan** [manns/pyspread#166]
So there is a trick used in the pyqtGraph project to support different python versions+engines
https://github.com/pyqtgraph/pyqtgraph/blob/develop/pyqtgraph/Qt.py

Its a `complete hack`, but there is one element I like and have used which is to support both pyside and PyQt5. I think it would be worth considering.

it goes something like this in psuedo code
```py
# Qt.py

# see if pyqt5 is there
try:
 from PyQt5.QtCore import Qt
 from PyQt5.QtCore import pyqtSignal
 from PyQt5 import QtCore
 from PyQt5 import QtNetwork 
 ...etc etc
except:
 from pyside.QtCore import Qt
 from pyside import pysideSignal as pyqtSignal
 from pyside import QtCore
 from pyside import QtNetwork 
 ...etc etc
```

Its then used as
```py
# foo.py

from Qt import Qt, pyqtsignal, QtWidgets, QtGui

class Foo(QtWidgets.QWidget):
   etc
```

**Comment by pedromorgan** [comment]
Here is an example project code using tecnique.. albeit only pyqt5 atmo
https://gitlab.com/open-geotechnical/ogt-py/tree/master/ogtgui

**Comment by manns** [comment]
pyside and pyqt can coexist on a platform. Is there a reason, why we should support both APIs?

Reasons against it:
 1) Our code has to be tested not only against multiple platforms (Windows 10, Windows 2019, Linux (various distributions)  but for each platform against multiple setups, at least Pyside, PySide2, PyQt. This makes a robust CI Integration a must, which eats up time for installing the latest versions on each platform.
 2) Potential future compatibility issues may annoy users.

**Comment by manns** [comment]
@pedromorgan If you send a patch to make pyspread comaptible with PySide, I am going to integrate it.
