### ISSUE TITLE
[python3] Mount external data in tabs

### ISSUE THREAD

**Issue by pedromorgan** [manns/pyspread#167]
So one idea in mind it to mount external data in a tab. such as

- a CSV file from a file eg on LAN
- a json url, that pulls data from a feed
- some data from an excel spreadsheet eg [openpyxl](https://openpyxl.readthedocs.io/en/stable/)
- and some data from an odf sheet eg [odfpy](https://github.com/eea/odfpy)

I notice the import csv which pips my curious and might have a go at.

**Comment by manns** [comment]
The original concept was to import external data either into cells or into one grid cell or into a variable by a macro that can be referred to from anywhere. 

In the python3 version, the macro panel is still missing, which makes working with csv more complicated. I was going to fix this soon after the matplotlib issues.

What function would be an external tab have for the user? Would it be a numpy array viewer such as in Spyder? Would it be a spawned Excel compatible spreadsheet such as gnumeric or LibreOffice Calc?
