### ISSUE TITLE
pyspread3: new repos

### ISSUE THREAD

**Issue by pedromorgan** [manns/pyspread#168]
This is a follow on from a comment https://github.com/manns/pyspread/issues/137#issuecomment-509438344

- so a requirements.txt  install takes 80% of time with large pyspread repos..
- can i suggest a new repos `pyspread3` and basically the python3 branch extracted
- pyspread3 is an indicator to the python version + generation
- a look at the history shows almost 99% commits are @manns 
- I don't think loosing history is an issue, and prefer a clean py3 slate

And continue from there...
we also need a critical TODO list so we can some hacker onboard ;-)

**Comment by pedromorgan** [comment]
This is maybe way thanks to StackOverflow

https://stackoverflow.com/questions/2227062/how-do-i-move-a-git-branch-out-into-its-own-repository

**Comment by manns** [comment]
I suggest that we polish the branch before creating a new repo.

Do you have experience with critical TODO lists? Please advise.

**Comment by retsyo** [comment]
I  do wish the pyspread3 is coded in PyQT. Because for anaconda, it seems that there is no PyQt for python 3 on windows 64, and it is not an easy way to build PyGTK on windows

**Comment by manns** [comment]
@retsyo You need wxPython for the python2 version of pyspread. You can download it at https://www.lfd.uci.edu/~gohlke/pythonlibs/
They can be installed via pip in Anaconda.
