### ISSUE TITLE
Add button to stop runaway macros

### ISSUE THREAD

**Issue by d601** [manns/pyspread#75]
I am not the best programmer, and sometimes I write scripts that don't function quite the way I intend. In the event that a macro enters an infinite loop and the whole program doesn't lock up, it would nice to be able to push a stop button so that I don't have to restart the program.

**Comment by manns** [comment]
I put this on low priority because I expect it easier to fix in Python3. Therefore, I postpone the activities to after the port.

**Comment by manns** [comment]
This will not be fixed in the Python2 branch.
Therefore, I am closing the issue.
